config/routes.rb
Rails.application.routes.draw do



  resources :admin_watchdogs
  resources :admin_logins
  resources :selfie_verifications,:except => [:new, :create]
  resources :address_verifications,:except => [:new, :create]
  resources :nationalid_verifications,:except => [:new, :create]
  resources :user_infos
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
    end
  end


  resources :admins,:except => [:new]
  resources :affilate_programs
  resources :countries
  resources :logins
  resources :verifications
  resources :watchdogs
  resources :users,:except => [:new]
  root "admins#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "admins#unlockaccount"
  get "two_factor" => "admins#get_two_factor"
  post "two_factor" => "admins#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "admin_log" => "admin_watchdogs#admin_log"
  get "statistics" => "admins#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "active_sessions" => "logins#active_sessions"
  get "admin_active_sessions" => "admin_logins#admin_active_sessions"
  get "send_confirmation_email" => "admins#send_confirmation_email"
  get "change_confirmation_code" => "admins#change_confirmation_code"
  get "confirm_google_code" => "admins#confirm_google_code"
  #get "affilate-program/:refered_by" => "affilate_programs#send_invitation"
  #post "send_invitation_email" => "affilate_programs#send_invitation_email"
  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "admins#add_admin"
  post "add_admin" => "admins#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "admin_logins#lock_page"
  post "lock_page" => "admin_logins#check_to_unlock"


  resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

  resource :session,
      controller: 'clearance/sessions',
      only: [:create]

  resources :admins,
      controller: 'admins',
      only: Clearance.configuration.user_actions do
        resource :password,
          controller: 'clearance/passwords',
          only: [:create, :edit, :update]
      end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
   get '/sign_up' => 'admins#new', as: 'sign_up'
  end
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<!-- ############ PAGE START-->
<div class="row no-gutter">
  <div class="col-sm-3 col-lg-2">
    <div class="p-y">
      <div class="nav-active-border left b-primary">
        <ul class="nav nav-sm flex-column">
          <li class="nav-item">
            <a class="nav-link block active" href data-toggle="tab" data-target="#tab-1">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link block" href data-toggle="tab" data-target="#tab-2">Account Settings</a>
          </li>
          <% if current_user.id == params[:id].to_i%> 
          <li class="nav-item">
            <a class="nav-link block" href data-toggle="tab" data-target="#tab-3">Two Factor Authentication</a>
          </li>
          <li class="nav-item">
            <a class="nav-link block" href data-toggle="tab" data-target="#tab-5">Security</a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-9 col-lg-10 light lt">
    <div class="tab-content pos-rlt">
      <div class="tab-pane active" id="tab-1">
        <div class="p-a-md dker _600">Public profile</div>
        <%= form_for @admin , html: {:class => 'p-a-md col-md-6', :id => "profile_#{@admin.id}"} do |form| %>
            <% if @admin.errors.any? %>
              <div id="error_explanation">
                  <%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved: 
                      <ul>
                          <% @admin.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                          <% end %>
                      </ul>
              </div>
            <% end %>
          <div class="form-group">
            <label>Profile Picture</label>
            <div class="form-file">
              <%= form.file_field :avatar %>
              <button class="btn white">Upload Picture</button>
            </div>
          </div>
      <% if current_user.roleid == 1 %> 
          <div class="form-group">
            <label>Email</label>
            <%= form.text_field :email, type: 'email',class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Username</label>
            <%= form.text_field :username,class: 'form-control' %>
          </div>
      <% end %>
          <div class="form-group">
            <label>First Name</label>
            <%= form.text_field :firstname,class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Last Name</label>
            <%= form.text_field :lastname,class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Country</label>
            <%= form.select(:country_id,  options_for_select(Country.all.collect {|p| [ p.Full_Name, p.id ] }, :selected => form.object.country_id ) ,{},  :class => 'form-control input-c' ) %>
          </div>
          <div class="form-group">
            <label>Telephone</label>
            <%= form.text_field :telephone,class: 'form-control' %>
            <span  class="mdl-textfield__error" id="wrong_code" style="color:red ; display:none;">Telephone number must be in the same Country</span>
          </div>
        <%# if current_user.roleid != 1 %>
          <div class="form-group">
            <label>Password</label>
            <%= form.password_field :confirm_password, :required => true,class: 'form-control' %>
          </div>
        <%# end %>
          <button type="submit" class="btn btn-info m-t">Update</button>
        <% end %>
      </div>
      <div class="tab-pane" id="tab-2">
        <div class="p-a-md dker _600">Account settings</div>
        <%= form_for @admin , html: {:class => 'p-a-md col-md-6', :id => "account_#{@admin.id}"} do |form| %>
            <% if @admin.errors.any? %>
                <div id="error_explanation">
                    <%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved: 
                       <ul>
                           <% @admin.errors.full_messages.each do |message| %>
                               <li><%= message %></li>
                           <% end %>
                       </ul>
                </div>
            <% end %> 
        
        <div class="form-group">
            <label>Secret Code</label>
            <%= form.text_field :secret_code,class: 'form-control' %>
          </div>
          <div class="form-group">
            <label>Account Currency</label>
            <%= form.select :account_currency, options_for_select( [["USD ",false],["Local Currency",true]], :selected => form.object.account_currency), {}, {:class => 'form-control'} %>
          </div>
          <div class="form-group">
            <label>Role</label>
            <%= form.select :roleid, options_for_select( [["admin","1"],["User","2"]], :selected => form.object.roleid),{}, {:class => 'form-control'} %>
          </div>  
          <div class="form-group">
            <label class="col-sm-2 form-control-label">Account Status</label>
                <label class="ui-switch ui-switch-lg m-t-xs m-r">
                    <%= form.check_box :disabled,{:selected => !(form.object.disabled)},false,true %>    
                    <i></i>
                </label>
          </div>                  
          <%# if current_user.roleid != 1 %>
          <div class="form-group">
            <label>Password</label>
            <%= form.password_field :confirm_password, :required => true,class: 'form-control' %>
          </div>
         <%# end %>
          <button type="submit" class="btn btn-info m-t" >Update</button>
        <% end %>
      </div>

<% if current_user.id == params[:id].to_i%>     
      <div class="tab-pane" id="tab-3">
      <div class="p-a-md dker _600">Active OTP</div>
      <div class="p-a-md">
        <div class="clearfix m-b-lg">
          <%= form_for @admin, html: {:class => 'col-md-6 p-a-0', :id => "authentication_#{@admin.id}"}  do |form| %>
            <% if @admin.errors.any? %>
               <div id="error_explanation">
                   <%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:
                   <ul>
                      <% @admin.errors.full_messages.each do |message| %>
                         <li><%= message %></li>
                      <% end %>
                   </ul>
               </div>
            <% end %>



       <div class="form-group">
            <label class="col-sm-2 form-control-label">Active OTP</label>
                  <div class="col-sm-10">
                        <label>Email Code</label>
                        <label class="ui-switch m-t-xs m-r">
                            <%= form.radio_button :active_otp, '1' %>                                 
                            <i></i>
                        </label>
                        <label>Google Code</label>
                             <label class="ui-switch m-t-xs m-r">
                             <%= form.radio_button :active_otp, '2' %>                                 
                             <i></i>
                        </label>
                  </div>
       </div>  
       <% if @admin.otp_secret_key != nil %>
            <div id="qrcode"></div><br><br><br><br><br>
       <% end %>         
            <div id="otp_code_details" style="display:none;">
                <label for="otp_secret_key">OTP Secret Key</label>
                    <input type="text" name="otp_secret_key" id="otp_secret_key"><br>
            </div>
            <div id="verify_form" style="display:none;">
                <div class="row">
                    <div class="col-lg-4 col-md-4">
                        <label>Code</label>
                        <input type="text" name="code" id="verifiy_code" >
                    </div>
                    <div class="col-lg-4">
                       <div  id="wrong_otp_code"; style="display:none; margin-top:30px;"><i class="fa fa-remove" style="color:red;"></i> <span class="text-muted"></span></div>
                       <div  id="correct_otp_code"; style="display:none; margin-top:30px;"><i class="fa fa-check" style="color:green;"></i> <span class="text-muted"></span></div>
                       </div>
                </div>
            </div>         
            <button type="submit" class="btn btn-info m-t" id="edit_setting">Update</button>
        <% end %>
        </div>        
      </div>
    </div>

      <div class="tab-pane" id="tab-5">
      <div class="p-a-md dker _600">Security</div>
      <div class="p-a-md">
        <div class="clearfix m-b-lg">
          <%= form_for @admin, html: {:class => 'col-md-6 p-a-0', :id => "security_#{@admin.id}"}  do |form| %>
             <% if @admin.errors.any? %>
               <div id="error_explanation">
                   <%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:
                   <ul>
                      <% @admin.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
               </div>
              <% end %>
          <%# if current_user.roleid != 1 %>
            <div class="form-group">
              <label>Old Password</label>
              <%= form.password_field :confirm_password, :required => true, class: 'form-control' %>
            </div>
          <%# end %>
            <div class="form-group">
              <label>New Password</label>
              <%= form.password_field :password, :required => true, class: 'form-control' %>
            </div>
            <button type="submit" class="btn btn-info m-t">Update</button>
          <% end %>
        </div>

        <p><strong>Delete account?</strong></p>
        <button type="submit" class="btn btn-danger m-t" data-toggle="modal" data-target="#modal">Delete Account</button>

      </div>
    </div>
    <% end %>
      
</div>


<!-- .modal -->
<div id="modal" class="modal fade animate black-overlay" data-backdrop="false">
  <div class="row-col h-v">
    <div class="row-cell v-m">
      <div class="modal-dialog modal-sm">
        <div class="modal-content flip-y">
          <div class="modal-body text-center">         
            <p class="p-y m-t"><i class="fa fa-remove text-warning fa-3x"></i></p>
            <p>Are you sure to delete your account?</p> 
          </div>
          <div class="modal-footer">
            <button type="button" class="btn white p-x-md" data-dismiss="modal">No</button>
            <button type="button" class="btn btn-danger p-x-md" data-dismiss="modal">Yes</button>
          </div>
        </div><!-- /.modal-content -->
      </div>
    </div>
  </div>
</div>
<!-- / .modal -->

<!-- ############ PAGE END-->

 

app/views/admins/add_admin.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>Add New Admin</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= form_for @admin , :url => add_admin_path do |form| %>
                    <% if @admin.errors.any? %>
                         <div id="error_explanation">
                             <%= pluralize(@admin.errors.count, "error") %> prohibited this user from being saved: 
                             <ul>
                                <% @admin.errors.full_messages.each do |message| %>
                                   <li><%= message %></li>
                                <% end %>
                             </ul>
                         </div>
                    <% end %>
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">User Name</label>
                                <div class="col-sm-10">
                                    <%= form.text_field :username , class: 'form-control' , :required => true %>
                                </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Email</label>
                                <div class="col-sm-10">
                                    <%= form.text_field :email, type: 'email' , class: 'form-control', :required => true %>
                                </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Password</label>
                               <div class="col-sm-10">
                                    <%= form.password_field :password , class: 'form-control' , :required => true %>
                               </div>
                      </div>
                      
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Country</label>
                             <div class="col-sm-10">
                                 <%= form.select :country_id, options_for_select( Country.all.collect {|p| [ p.Full_Name, p.id ] } ), {}, {:class => 'form-control c-select'} %>
                             </div>
                      </div>

                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Account Status</label>
                               <label class="ui-switch ui-switch-lg m-t-xs m-r">
                                    <%= form.check_box :disabled,{:checked => !@admin.disabled},0,1 %>    
                                    <i></i>
                               </label>
                      </div>

                       <div class="form-group row m-t-md">
                           <div class="col-sm-offset-2 col-sm-10">
                               <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                           </div>
                       </div>
                <% end %>
            </div>
    </div>
</div>
    

app/views/admins/create.html.erb
<%= debug params%>

app/views/admins/edit_password.html.erb
<h1>Editing User Password </h1>
    <%= form_for @user do |form| %>
        <% if @user.errors.any? %>
           <div id="error_explanation">
               <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
               <ul>
                   <% @user.errors.full_messages.each do |message| %>
                       <li><%= message %></li>
                   <% end %>
               </ul>
           </div>
       <% end %>

       <div class="password-field">
            <%= form.label :password %>
            <%= form.password_field :password %>
       </div><br>

       <div class="password-field">
            <%= form.label :confirm_password %>
            <%= form.password_field :confirm_password %>
       </div><br>

       <div class="submit-field">
             <%= form.submit  %>
       </div>
    <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/admins/get_two_factor.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payers - Payment Facilator</title>
  <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- for ios 7 style, multi-resolution icon of 152x152 -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
  <link rel="apple-touch-icon" href="/assets/images/logo.png">
  <meta name="apple-mobile-web-app-title" content="Flatkit">
  <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="shortcut icon" sizes="196x196" href="/assets/images/logo.png">
  
  <!-- style -->
  <link rel="stylesheet" href="/assets/animate.css/animate.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/glyphicons/glyphicons.css" type="text/css" />
  <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/material-design-icons/material-design-icons.css" type="text/css" />

  <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
  <!-- build:css ../assets/styles/app.min.css -->
  <link rel="stylesheet" href="/assets/styles/app.css" type="text/css" />
  <!-- endbuild -->
  <link rel="stylesheet" href="/assets/styles/font.css" type="text/css" />
</head>
<body>
  <div class="app" id="app">
  <% flash.each do |key, value| -%>
    <div class="col-sm-3">
            <div class="box-color accent pos-rlt">
              <span class="arrow bottom b-accent"></span>
              <div class="box-body">
                 <div id="flash_<%= key %>"><%=h value %></div>
              </div>
            </div>
    </div>
  <% end %>
<!-- ############ LAYOUT START-->
  <div class="center-block w-xxl w-auto-xs p-y-md">
    <div class="navbar">
      <div class="pull-center">
        <div ui-include="'/views/blocks/navbar.brand.html'"></div>
      </div>
    </div>
    <div class="p-a-md box-color r box-shadow-z1 text-color m-a">
	  <div class="m-b text-sm">
		<% if current_user.active_otp == 1%>
			Email Code Authentication
		<% else %>
			Google Authentication
		<% end %>
        
      </div>
      <%= form_for :confirm , :url => two_factor_path do |f| %>
		<div class="md-form-group float-label">
		  <%= f.text_field :code , class: 'md-input', :required => true %>
          <label>Authentication Code</label>
        </div>
              
        <button type="submit" class="btn primary btn-block p-x-md">Send</button>
	  <% end %>
    </div>
    <% if current_user.active_otp == 2 %>
        <div class="p-v-lg text-center">
            <div class="m-b"><a ui-sref="access.forgot-password" href="/send_confirmation_email" class="text-primary _600">has a problem with google authentication?, confirm by Email</a></div>		
    </div>
    
	<% end %>   
    
  </div>

  <div class="p-v-lg text-center">
      <div><a ui-sref="access.signin" href="" class="text-primary _600"><%= button_to "Sign Out", sign_out_path, method: :delete, class: "btn btn-sm accent"%></a></div>
  </div>
  
<!-- ############ LAYOUT END-->

  </div>
<!-- build:js scripts/app.html.js -->
<!-- jQuery -->
  <script src="/libs/jquery/jquery/dist/jquery.js"></script>
<!-- Bootstrap -->
  <script src="/libs/jquery/tether/dist/js/tether.min.js"></script>
  <script src="/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
<!-- core -->
  <script src="/libs/jquery/underscore/underscore-min.js"></script>
  <script src="/libs/jquery/jQuery-Storage-API/jquery.storageapi.min.js"></script>
  <script src="/libs/jquery/PACE/pace.min.js"></script>

  <script src="scripts/config.lazyload.js"></script>

  <script src="/scripts/palette.js"></script>
  <script src="/scripts/ui-load.js"></script>
  <script src="/scripts/ui-jp.js"></script>
  <script src="/scripts/ui-include.js"></script>
  <script src="/scripts/ui-device.js"></script>
  <script src="/scripts/ui-form.js"></script>
  <script src="/scripts/ui-nav.js"></script>
  <script src="/scripts/ui-screenfull.js"></script>
  <script src="/scripts/ui-scroll-to.js"></script>
  <script src="/scripts/ui-toggle-class.js"></script>

  <script src="/scripts/app.js"></script>

  <!-- ajax -->
  <script src="/libs/jquery/jquery-pjax/jquery.pjax.js"></script>
  <script src="/scripts/ajax.js"></script>
<!-- endbuild -->
</body>
</html>

app/views/admins/index.html.erb
<!-- ############ PAGE START-->
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Admin</h2>
      <small>List of all admins</small>
    </div>
    <div class="box-body">
      Search: <input id="filter" type="text" class="form-control input-sm w-auto inline m-r"/>
      <% if current_user and current_user.roleid == 1 %>
           <%= link_to 'Add New Admin', add_admin_path, {:class => 'btn btn-fw accent',:style => "margin-left:600px;"}%>
      <% end %>
    </div>
    <div>
      <table class="table m-b-none" ui-jp="footable" data-filter="#filter" data-page-size="5">
        <thead>
          <tr>
              <th data-toggle="true">
              Username
              </th>
              <th>
              Email
              </th>
              <!-- <th data-hide="phone,tablet">
              Job Title
              </th>
              <th data-hide="phone,tablet" data-name="Date Of Birth">
                  DOB
              </th> --> 
              <th data-hide="phone">
              Account Status
              </th>
          </tr>
        </thead>
        <tbody>
        <% @admins.each do |admin| %>
          <tr>
              <td><%= admin.username %></td>
              <td><%= admin.email %></td>
              <!-- <td>Traffic Court Referee</td>
              <td data-value="78025368997">22 Jun 1972</td> -->
              <% if admin.status == 1 and admin.disabled == 0 %>
                <td data-value="1"><span class="label success" title="Active">Active</span></td>
              <% elsif admin.disabled == 1 %>
                <td data-value="2"><span class="label" title="Disabled">Disabled</span></td>
              <% elsif admin.status == 0 %>
                <td data-value="3"><span class="label warning" title="Suspended">Suspended</span></td>
              <% end %>
              <td><%= link_to 'Show', admin %></td>
              
          </tr>
          <% end %>
          
        </tbody>
        <tfoot class="hide-if-no-paging">
          <tr>
              <td colspan="5" class="text-center">
                  <ul class="pagination"></ul>
              </td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

<!-- ############ PAGE END-->

app/views/admins/post_two_factor.html.erb
<%= debug @user_code%>
<%= debug @sent_code %>

app/views/admins/show.html.erb
<div class="padding">
  
      <div class="box">
        <div class="box-header">
          <span class="label danger pull-right"><%= @admin.id %></span>
          <h3>Admin Profile</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Username</th>
              <td><%= @admin.username %></td>
            </tr>
          </thead>
          <tbody>
          <%# if @admin.avatar.attached? %>
            <!-- <tr>
              <th>Profile Picture</th>
              <td> <%# image_tag @admin.avatar.variant(resize: "100x100")  %></td>
            </tr> -->
          <%# end %>
            <tr>
              <th>firstname</th>
              <td> <%= @admin.firstname %></td>
            </tr>
            <tr>
              <th>lastname</th>
              <td> <%= @admin.lastname %></td>
            </tr>
            <tr>
              <th>Email</th>
              <td> <%= @admin.email %></td>
            </tr>
            <tr>
              <th>account_number</th>
              <td> <%= @admin.account_number %></td>
            </tr>
            <tr>
              <th>uuid</th>
              <td> <%= @admin.uuid %></td>
            </tr>
            <tr>
              <th>telephone</th>
              <td> <%= @admin.telephone %></td>
            </tr>
            <tr>
              <th>roleid</th>
              <td> <%= @admin.roleid %></td>
            </tr>
            <tr>
              <th>country</th>
              <td> <%= @admin.country.Full_Name %></td>
            </tr>
            <tr>
              <th>Account Currency</th>
                <% if !(@admin.account_currency)%>
                   <td> <%= "USD" %></td>
                <% else %>
                   <td> <%= @admin.country.Currency %></td>
                <% end%>
            </tr> 
          <% if @admin.secret_code != nil and @admin.secret_code != "" %>                
            <tr>
              <th>Secret Code</th>
              <td><%= "********" + @admin.secret_code[@admin.secret_code.length - 3 ,3] %></td>
            </tr> 
          <% end %>                
            <tr>
              <th>Active Otp</th>
              <% if @admin.active_otp == 1 %>
                  <td> <%= "Email Code" %></td>
              <% elsif @admin.active_otp == 2 %>
                  <td> <%= "Google Authentication Code" %></td>
              <% end %>              
            </tr>
            <tr>
            
            <tr>
              <th>Other Links</th>
              <td> <%= link_to 'Edit Profile', edit_admin_path(@admin) %> - <%= link_to 'show admin log'.html_safe, { :controller => :admin_watchdogs,:action=>:admin_log,:id => @admin.id} %> - <%= link_to t('show active sessions').html_safe, { :controller => :admin_logins,:action=>:admin_active_sessions,:id => @admin.id} %> - </td>
            </tr>
            
                    
           
          </tbody>
        </table>
      </div>
</div>

app/views/admins/statistics.html.erb
<div class="card" style="width:20%; height:60%; background:#afb8cf; box-shadow: 0 0 8px #5c558d; margin-bottom:20px; padding-bottom:10px; padding-top:5px; margin-top:20px;">
<%= form_tag  url_for(:controller => 'users', :action => 'statistics'), :method => 'get' do %>

    <div class="page-title l-height-md mrg-bottom-md">
        <div class="row row-default button-row">
            <div class="col-md-3">
                <h4 class="iblock mrg-left-lg md-lg-fontsize text-dbrand font-weight-normal">
                    <%= t('Users statistics') %>
                </h4>
            </div>
            <div class="col-md-9">
                <div class="clearfix">                                        
                    <div class="field">                                   
                    <%= select_tag(:account_status, options_for_select([["جميع الأعضاء","count_users"],["الأعضاء المفعلين","confirmed"],["الأعضاء الموقوفين","disabled"]]),:include_blank =>  t('choose from list'))%>
                        <br><br><button type="submit" style="margin-top: -7px" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= 'search' %> </button>
                    </div>    
                </div>
            </div>
        </div>
    </div>    
<% end %>
  <br>
<%= "sum = " + @result.count.to_s%>
</div>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @result.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if user.disabled == 0 %>
        <td><%= link_to t('Disable User').html_safe, { :controller => :users,:action=>:lock_unlock_account,:id => user.id} %></td>
        <% else %>
        <td><%= link_to t('Enable User').html_safe, { :controller => :users,:action=>:lock_unlock_account,:id => user.id} %></td>
        <% end %>
        <td><%= link_to t('show user log').html_safe, { :controller => :watchdogs,:action=>:user_log,:id => user.id} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script language="JavaScript" type="text/javascript" src="/assets/js/jquery-3.2.1.min.js"></script>

<script>
$(document).ready(function() {
    $("#account_status").val("<%= params[:account_status].to_s%>");
    })
</script>

app/views/admins/update.html.erb
<%= debug params %>
<%= debug params[:user][:confirm_password] %>
<%= debug params[:confirm_password] %>